import ServicePhoneSvg from "@/assets/images/home/service-phone.svg";
import ServiceLocationSvg from "@/assets/images/home/service-location.svg";
import ServicePetsSvg from "@/assets/images/home/service-pets.svg";

export const SERVICE_LIST = [
  {
    img: ServicePhoneSvg,
    title: "快速便捷",
    content:
      "操作介面簡單易懂，您只需幾個步驟就能完成預約。無需排隊或繁瑣的手續，讓您節省時間，輕鬆安排寵物看診。",
  },
  {
    img: ServiceLocationSvg,
    title: "遍佈全國",
    content:
      "整合全國合法的獸醫院，讓您輕鬆找到附近的專業診所。無論是日常檢查、緊急救助還是專科治療，我們都能滿足您的需求。",
  },
  {
    img: ServicePetsSvg,
    title: "健康管理",
    content:
      "內建寵物健康紀錄功能，讓您輕鬆追蹤疫苗接種、疾病治療和年度檢查進度。還會貼心提醒您每個重要時刻，讓您的毛孩健康無憂！",
  },
];

export const cities = [
  { city: "基隆市" },
  { city: "臺北市" },
  { city: "新北市" },
  { city: "桃園市" },
  { city: "新竹市" },
  { city: "新竹縣" },
  { city: "苗栗縣" },
  { city: "臺中市" },
  { city: "彰化縣" },
  { city: "雲林縣" },
  { city: "嘉義市" },
  { city: "嘉義縣" },
  { city: "臺南市" },
  { city: "屏東縣" },
  { city: "臺東縣" },
  { city: "花蓮縣" },
  { city: "宜蘭縣" },
  { city: "南投縣" },
  { city: "高雄市" },
  { city: "連江縣" },
  { city: "金門縣" },
  { city: "澎湖縣" },
];

export const districts = [
  { city: "連江縣", dist: "南竿鄉" },
  { city: "連江縣", dist: "北竿鄉" },
  { city: "連江縣", dist: "莒光鄉" },
  { city: "連江縣", dist: "東引鄉" },
  { city: "金門縣", dist: "金城鎮" },
  { city: "金門縣", dist: "金沙鎮" },
  { city: "金門縣", dist: "金湖鎮" },
  { city: "金門縣", dist: "金寧鄉" },
  { city: "金門縣", dist: "烈嶼鄉" },
  { city: "金門縣", dist: "烏坵鄉" },
  { city: "宜蘭縣", dist: "宜蘭市" },
  { city: "宜蘭縣", dist: "羅東鎮" },
  { city: "宜蘭縣", dist: "蘇澳鎮" },
  { city: "宜蘭縣", dist: "頭城鎮" },
  { city: "宜蘭縣", dist: "礁溪鄉" },
  { city: "宜蘭縣", dist: "壯圍鄉" },
  { city: "宜蘭縣", dist: "員山鄉" },
  { city: "宜蘭縣", dist: "冬山鄉" },
  { city: "宜蘭縣", dist: "五結鄉" },
  { city: "宜蘭縣", dist: "三星鄉" },
  { city: "宜蘭縣", dist: "大同鄉" },
  { city: "宜蘭縣", dist: "南澳鄉" },
  { city: "新竹縣", dist: "竹北市" },
  { city: "新竹縣", dist: "竹東鎮" },
  { city: "新竹縣", dist: "新埔鎮" },
  { city: "新竹縣", dist: "關西鎮" },
  { city: "新竹縣", dist: "湖口鄉" },
  { city: "新竹縣", dist: "新豐鄉" },
  { city: "新竹縣", dist: "芎林鄉" },
  { city: "新竹縣", dist: "橫山鄉" },
  { city: "新竹縣", dist: "北埔鄉" },
  { city: "新竹縣", dist: "寶山鄉" },
  { city: "新竹縣", dist: "峨眉鄉" },
  { city: "新竹縣", dist: "尖石鄉" },
  { city: "新竹縣", dist: "五峰鄉" },
  { city: "苗栗縣", dist: "苗栗市" },
  { city: "苗栗縣", dist: "苑裡鎮" },
  { city: "苗栗縣", dist: "通霄鎮" },
  { city: "苗栗縣", dist: "竹南鎮" },
  { city: "苗栗縣", dist: "頭份市" },
  { city: "苗栗縣", dist: "後龍鎮" },
  { city: "苗栗縣", dist: "卓蘭鎮" },
  { city: "苗栗縣", dist: "大湖鄉" },
  { city: "苗栗縣", dist: "公館鄉" },
  { city: "苗栗縣", dist: "銅鑼鄉" },
  { city: "苗栗縣", dist: "南庄鄉" },
  { city: "苗栗縣", dist: "頭屋鄉" },
  { city: "苗栗縣", dist: "三義鄉" },
  { city: "苗栗縣", dist: "西湖鄉" },
  { city: "苗栗縣", dist: "造橋鄉" },
  { city: "苗栗縣", dist: "三灣鄉" },
  { city: "苗栗縣", dist: "獅潭鄉" },
  { city: "苗栗縣", dist: "泰安鄉" },
  { city: "彰化縣", dist: "彰化市" },
  { city: "彰化縣", dist: "鹿港鎮" },
  { city: "彰化縣", dist: "和美鎮" },
  { city: "彰化縣", dist: "線西鄉" },
  { city: "彰化縣", dist: "伸港鄉" },
  { city: "彰化縣", dist: "福興鄉" },
  { city: "彰化縣", dist: "秀水鄉" },
  { city: "彰化縣", dist: "花壇鄉" },
  { city: "彰化縣", dist: "芬園鄉" },
  { city: "彰化縣", dist: "員林市" },
  { city: "彰化縣", dist: "溪湖鎮" },
  { city: "彰化縣", dist: "田中鎮" },
  { city: "彰化縣", dist: "大村鄉" },
  { city: "彰化縣", dist: "埔鹽鄉" },
  { city: "彰化縣", dist: "埔心鄉" },
  { city: "彰化縣", dist: "永靖鄉" },
  { city: "彰化縣", dist: "社頭鄉" },
  { city: "彰化縣", dist: "二水鄉" },
  { city: "彰化縣", dist: "北斗鎮" },
  { city: "彰化縣", dist: "二林鎮" },
  { city: "彰化縣", dist: "田尾鄉" },
  { city: "彰化縣", dist: "埤頭鄉" },
  { city: "彰化縣", dist: "芳苑鄉" },
  { city: "彰化縣", dist: "大城鄉" },
  { city: "彰化縣", dist: "竹塘鄉" },
  { city: "彰化縣", dist: "溪州鄉" },
  { city: "南投縣", dist: "南投市" },
  { city: "南投縣", dist: "埔里鎮" },
  { city: "南投縣", dist: "草屯鎮" },
  { city: "南投縣", dist: "竹山鎮" },
  { city: "南投縣", dist: "集集鎮" },
  { city: "南投縣", dist: "名間鄉" },
  { city: "南投縣", dist: "鹿谷鄉" },
  { city: "南投縣", dist: "中寮鄉" },
  { city: "南投縣", dist: "魚池鄉" },
  { city: "南投縣", dist: "國姓鄉" },
  { city: "南投縣", dist: "水里鄉" },
  { city: "南投縣", dist: "信義鄉" },
  { city: "南投縣", dist: "仁愛鄉" },
  { city: "雲林縣", dist: "斗六市" },
  { city: "雲林縣", dist: "斗南鎮" },
  { city: "雲林縣", dist: "虎尾鎮" },
  { city: "雲林縣", dist: "西螺鎮" },
  { city: "雲林縣", dist: "土庫鎮" },
  { city: "雲林縣", dist: "北港鎮" },
  { city: "雲林縣", dist: "古坑鄉" },
  { city: "雲林縣", dist: "大埤鄉" },
  { city: "雲林縣", dist: "莿桐鄉" },
  { city: "雲林縣", dist: "林內鄉" },
  { city: "雲林縣", dist: "二崙鄉" },
  { city: "雲林縣", dist: "崙背鄉" },
  { city: "雲林縣", dist: "麥寮鄉" },
  { city: "雲林縣", dist: "東勢鄉" },
  { city: "雲林縣", dist: "褒忠鄉" },
  { city: "雲林縣", dist: "臺西鄉" },
  { city: "雲林縣", dist: "元長鄉" },
  { city: "雲林縣", dist: "四湖鄉" },
  { city: "雲林縣", dist: "口湖鄉" },
  { city: "雲林縣", dist: "水林鄉" },
  { city: "嘉義縣", dist: "太保市" },
  { city: "嘉義縣", dist: "朴子市" },
  { city: "嘉義縣", dist: "布袋鎮" },
  { city: "嘉義縣", dist: "大林鎮" },
  { city: "嘉義縣", dist: "民雄鄉" },
  { city: "嘉義縣", dist: "溪口鄉" },
  { city: "嘉義縣", dist: "新港鄉" },
  { city: "嘉義縣", dist: "六腳鄉" },
  { city: "嘉義縣", dist: "東石鄉" },
  { city: "嘉義縣", dist: "義竹鄉" },
  { city: "嘉義縣", dist: "鹿草鄉" },
  { city: "嘉義縣", dist: "水上鄉" },
  { city: "嘉義縣", dist: "中埔鄉" },
  { city: "嘉義縣", dist: "竹崎鄉" },
  { city: "嘉義縣", dist: "梅山鄉" },
  { city: "嘉義縣", dist: "番路鄉" },
  { city: "嘉義縣", dist: "大埔鄉" },
  { city: "嘉義縣", dist: "阿里山鄉" },
  { city: "屏東縣", dist: "屏東市" },
  { city: "屏東縣", dist: "潮州鎮" },
  { city: "屏東縣", dist: "東港鎮" },
  { city: "屏東縣", dist: "恆春鎮" },
  { city: "屏東縣", dist: "萬丹鄉" },
  { city: "屏東縣", dist: "長治鄉" },
  { city: "屏東縣", dist: "麟洛鄉" },
  { city: "屏東縣", dist: "九如鄉" },
  { city: "屏東縣", dist: "里港鄉" },
  { city: "屏東縣", dist: "鹽埔鄉" },
  { city: "屏東縣", dist: "高樹鄉" },
  { city: "屏東縣", dist: "萬巒鄉" },
  { city: "屏東縣", dist: "內埔鄉" },
  { city: "屏東縣", dist: "竹田鄉" },
  { city: "屏東縣", dist: "新埤鄉" },
  { city: "屏東縣", dist: "枋寮鄉" },
  { city: "屏東縣", dist: "新園鄉" },
  { city: "屏東縣", dist: "崁頂鄉" },
  { city: "屏東縣", dist: "林邊鄉" },
  { city: "屏東縣", dist: "南州鄉" },
  { city: "屏東縣", dist: "佳冬鄉" },
  { city: "屏東縣", dist: "琉球鄉" },
  { city: "屏東縣", dist: "車城鄉" },
  { city: "屏東縣", dist: "滿州鄉" },
  { city: "屏東縣", dist: "枋山鄉" },
  { city: "屏東縣", dist: "三地門鄉" },
  { city: "屏東縣", dist: "霧臺鄉" },
  { city: "屏東縣", dist: "瑪家鄉" },
  { city: "屏東縣", dist: "泰武鄉" },
  { city: "屏東縣", dist: "來義鄉" },
  { city: "屏東縣", dist: "春日鄉" },
  { city: "屏東縣", dist: "獅子鄉" },
  { city: "屏東縣", dist: "牡丹鄉" },
  { city: "臺東縣", dist: "臺東市" },
  { city: "臺東縣", dist: "成功鎮" },
  { city: "臺東縣", dist: "關山鎮" },
  { city: "臺東縣", dist: "卑南鄉" },
  { city: "臺東縣", dist: "鹿野鄉" },
  { city: "臺東縣", dist: "池上鄉" },
  { city: "臺東縣", dist: "東河鄉" },
  { city: "臺東縣", dist: "長濱鄉" },
  { city: "臺東縣", dist: "太麻里鄉" },
  { city: "臺東縣", dist: "大武鄉" },
  { city: "臺東縣", dist: "綠島鄉" },
  { city: "臺東縣", dist: "海端鄉" },
  { city: "臺東縣", dist: "延平鄉" },
  { city: "臺東縣", dist: "金峰鄉" },
  { city: "臺東縣", dist: "達仁鄉" },
  { city: "臺東縣", dist: "蘭嶼鄉" },
  { city: "花蓮縣", dist: "花蓮市" },
  { city: "花蓮縣", dist: "鳳林鎮" },
  { city: "花蓮縣", dist: "玉里鎮" },
  { city: "花蓮縣", dist: "新城鄉" },
  { city: "花蓮縣", dist: "吉安鄉" },
  { city: "花蓮縣", dist: "壽豐鄉" },
  { city: "花蓮縣", dist: "光復鄉" },
  { city: "花蓮縣", dist: "豐濱鄉" },
  { city: "花蓮縣", dist: "瑞穗鄉" },
  { city: "花蓮縣", dist: "富里鄉" },
  { city: "花蓮縣", dist: "秀林鄉" },
  { city: "花蓮縣", dist: "萬榮鄉" },
  { city: "花蓮縣", dist: "卓溪鄉" },
  { city: "澎湖縣", dist: "馬公市" },
  { city: "澎湖縣", dist: "湖西鄉" },
  { city: "澎湖縣", dist: "白沙鄉" },
  { city: "澎湖縣", dist: "西嶼鄉" },
  { city: "澎湖縣", dist: "望安鄉" },
  { city: "澎湖縣", dist: "七美鄉" },
  { city: "基隆市", dist: "中正區" },
  { city: "基隆市", dist: "七堵區" },
  { city: "基隆市", dist: "暖暖區" },
  { city: "基隆市", dist: "仁愛區" },
  { city: "基隆市", dist: "中山區" },
  { city: "基隆市", dist: "安樂區" },
  { city: "基隆市", dist: "信義區" },
  { city: "新竹市", dist: "東區" },
  { city: "新竹市", dist: "北區" },
  { city: "新竹市", dist: "香山區" },
  { city: "嘉義市", dist: "東區" },
  { city: "嘉義市", dist: "西區" },
  { city: "臺北市", dist: "松山區" },
  { city: "臺北市", dist: "信義區" },
  { city: "臺北市", dist: "大安區" },
  { city: "臺北市", dist: "中山區" },
  { city: "臺北市", dist: "中正區" },
  { city: "臺北市", dist: "大同區" },
  { city: "臺北市", dist: "萬華區" },
  { city: "臺北市", dist: "文山區" },
  { city: "臺北市", dist: "南港區" },
  { city: "臺北市", dist: "內湖區" },
  { city: "臺北市", dist: "士林區" },
  { city: "臺北市", dist: "北投區" },
  { city: "高雄市", dist: "鹽埕區" },
  { city: "高雄市", dist: "鼓山區" },
  { city: "高雄市", dist: "左營區" },
  { city: "高雄市", dist: "楠梓區" },
  { city: "高雄市", dist: "三民區" },
  { city: "高雄市", dist: "新興區" },
  { city: "高雄市", dist: "前金區" },
  { city: "高雄市", dist: "苓雅區" },
  { city: "高雄市", dist: "前鎮區" },
  { city: "高雄市", dist: "旗津區" },
  { city: "高雄市", dist: "小港區" },
  { city: "高雄市", dist: "鳳山區" },
  { city: "高雄市", dist: "林園區" },
  { city: "高雄市", dist: "大寮區" },
  { city: "高雄市", dist: "大樹區" },
  { city: "高雄市", dist: "大社區" },
  { city: "高雄市", dist: "仁武區" },
  { city: "高雄市", dist: "鳥松區" },
  { city: "高雄市", dist: "岡山區" },
  { city: "高雄市", dist: "橋頭區" },
  { city: "高雄市", dist: "燕巢區" },
  { city: "高雄市", dist: "田寮區" },
  { city: "高雄市", dist: "阿蓮區" },
  { city: "高雄市", dist: "路竹區" },
  { city: "高雄市", dist: "湖內區" },
  { city: "高雄市", dist: "茄萣區" },
  { city: "高雄市", dist: "永安區" },
  { city: "高雄市", dist: "彌陀區" },
  { city: "高雄市", dist: "梓官區" },
  { city: "高雄市", dist: "旗山區" },
  { city: "高雄市", dist: "美濃區" },
  { city: "高雄市", dist: "六龜區" },
  { city: "高雄市", dist: "甲仙區" },
  { city: "高雄市", dist: "杉林區" },
  { city: "高雄市", dist: "內門區" },
  { city: "高雄市", dist: "茂林區" },
  { city: "高雄市", dist: "桃源區" },
  { city: "高雄市", dist: "那瑪夏區" },
  { city: "新北市", dist: "板橋區" },
  { city: "新北市", dist: "三重區" },
  { city: "新北市", dist: "中和區" },
  { city: "新北市", dist: "永和區" },
  { city: "新北市", dist: "新莊區" },
  { city: "新北市", dist: "新店區" },
  { city: "新北市", dist: "樹林區" },
  { city: "新北市", dist: "鶯歌區" },
  { city: "新北市", dist: "三峽區" },
  { city: "新北市", dist: "淡水區" },
  { city: "新北市", dist: "汐止區" },
  { city: "新北市", dist: "瑞芳區" },
  { city: "新北市", dist: "土城區" },
  { city: "新北市", dist: "蘆洲區" },
  { city: "新北市", dist: "五股區" },
  { city: "新北市", dist: "泰山區" },
  { city: "新北市", dist: "林口區" },
  { city: "新北市", dist: "深坑區" },
  { city: "新北市", dist: "石碇區" },
  { city: "新北市", dist: "坪林區" },
  { city: "新北市", dist: "三芝區" },
  { city: "新北市", dist: "石門區" },
  { city: "新北市", dist: "八里區" },
  { city: "新北市", dist: "平溪區" },
  { city: "新北市", dist: "雙溪區" },
  { city: "新北市", dist: "貢寮區" },
  { city: "新北市", dist: "金山區" },
  { city: "新北市", dist: "萬里區" },
  { city: "新北市", dist: "烏來區" },
  { city: "臺中市", dist: "中區" },
  { city: "臺中市", dist: "東區" },
  { city: "臺中市", dist: "南區" },
  { city: "臺中市", dist: "西區" },
  { city: "臺中市", dist: "北區" },
  { city: "臺中市", dist: "西屯區" },
  { city: "臺中市", dist: "南屯區" },
  { city: "臺中市", dist: "北屯區" },
  { city: "臺中市", dist: "豐原區" },
  { city: "臺中市", dist: "東勢區" },
  { city: "臺中市", dist: "大甲區" },
  { city: "臺中市", dist: "清水區" },
  { city: "臺中市", dist: "沙鹿區" },
  { city: "臺中市", dist: "梧棲區" },
  { city: "臺中市", dist: "后里區" },
  { city: "臺中市", dist: "神岡區" },
  { city: "臺中市", dist: "潭子區" },
  { city: "臺中市", dist: "大雅區" },
  { city: "臺中市", dist: "新社區" },
  { city: "臺中市", dist: "石岡區" },
  { city: "臺中市", dist: "外埔區" },
  { city: "臺中市", dist: "大安區" },
  { city: "臺中市", dist: "烏日區" },
  { city: "臺中市", dist: "大肚區" },
  { city: "臺中市", dist: "龍井區" },
  { city: "臺中市", dist: "霧峰區" },
  { city: "臺中市", dist: "太平區" },
  { city: "臺中市", dist: "大里區" },
  { city: "臺中市", dist: "和平區" },
  { city: "臺南市", dist: "新營區" },
  { city: "臺南市", dist: "鹽水區" },
  { city: "臺南市", dist: "白河區" },
  { city: "臺南市", dist: "柳營區" },
  { city: "臺南市", dist: "後壁區" },
  { city: "臺南市", dist: "東山區" },
  { city: "臺南市", dist: "麻豆區" },
  { city: "臺南市", dist: "下營區" },
  { city: "臺南市", dist: "六甲區" },
  { city: "臺南市", dist: "官田區" },
  { city: "臺南市", dist: "大內區" },
  { city: "臺南市", dist: "佳里區" },
  { city: "臺南市", dist: "學甲區" },
  { city: "臺南市", dist: "西港區" },
  { city: "臺南市", dist: "七股區" },
  { city: "臺南市", dist: "將軍區" },
  { city: "臺南市", dist: "北門區" },
  { city: "臺南市", dist: "新化區" },
  { city: "臺南市", dist: "善化區" },
  { city: "臺南市", dist: "新市區" },
  { city: "臺南市", dist: "安定區" },
  { city: "臺南市", dist: "山上區" },
  { city: "臺南市", dist: "玉井區" },
  { city: "臺南市", dist: "楠西區" },
  { city: "臺南市", dist: "南化區" },
  { city: "臺南市", dist: "左鎮區" },
  { city: "臺南市", dist: "仁德區" },
  { city: "臺南市", dist: "歸仁區" },
  { city: "臺南市", dist: "關廟區" },
  { city: "臺南市", dist: "龍崎區" },
  { city: "臺南市", dist: "永康區" },
  { city: "臺南市", dist: "東區" },
  { city: "臺南市", dist: "南區" },
  { city: "臺南市", dist: "北區" },
  { city: "臺南市", dist: "安南區" },
  { city: "臺南市", dist: "安平區" },
  { city: "臺南市", dist: "中西區" },
  { city: "桃園市", dist: "桃園區" },
  { city: "桃園市", dist: "中壢區" },
  { city: "桃園市", dist: "大溪區" },
  { city: "桃園市", dist: "楊梅區" },
  { city: "桃園市", dist: "蘆竹區" },
  { city: "桃園市", dist: "大園區" },
  { city: "桃園市", dist: "龜山區" },
  { city: "桃園市", dist: "八德區" },
  { city: "桃園市", dist: "龍潭區" },
  { city: "桃園市", dist: "平鎮區" },
  { city: "桃園市", dist: "新屋區" },
  { city: "桃園市", dist: "觀音區" },
  { city: "桃園市", dist: "復興區" },
];

export const cityQueryDistricts = {
  "連江縣": [
    { dist: "南竿鄉" },
    { dist: "北竿鄉" },
    { dist: "莒光鄉" },
    { dist: "東引鄉" }
  ],
  "金門縣": [
    { dist: "金城鎮" },
    { dist: "金沙鎮" },
    { dist: "金湖鎮" },
    { dist: "金寧鄉" },
    { dist: "烈嶼鄉" },
    { dist: "烏坵鄉" }
  ],
  "宜蘭縣": [
    { dist: "宜蘭市" },
    { dist: "羅東鎮" },
    { dist: "蘇澳鎮" },
    { dist: "頭城鎮" },
    { dist: "礁溪鄉" },
    { dist: "壯圍鄉" },
    { dist: "員山鄉" },
    { dist: "冬山鄉" },
    { dist: "五結鄉" },
    { dist: "三星鄉" },
    { dist: "大同鄉" },
    { dist: "南澳鄉" }
  ],
  "新竹縣": [
    { dist: "竹北市" },
    { dist: "竹東鎮" },
    { dist: "新埔鎮" },
    { dist: "關西鎮" },
    { dist: "湖口鄉" },
    { dist: "新豐鄉" },
    { dist: "芎林鄉" },
    { dist: "橫山鄉" },
    { dist: "北埔鄉" },
    { dist: "寶山鄉" },
    { dist: "峨眉鄉" },
    { dist: "尖石鄉" },
    { dist: "五峰鄉" }
  ],
  "苗栗縣": [
    { dist: "苗栗市" },
    { dist: "苑裡鎮" },
    { dist: "通霄鎮" },
    { dist: "竹南鎮" },
    { dist: "頭份市" },
    { dist: "後龍鎮" },
    { dist: "卓蘭鎮" },
    { dist: "大湖鄉" },
    { dist: "公館鄉" },
    { dist: "銅鑼鄉" },
    { dist: "南庄鄉" },
    { dist: "頭屋鄉" },
    { dist: "三義鄉" },
    { dist: "西湖鄉" },
    { dist: "造橋鄉" },
    { dist: "三灣鄉" },
    { dist: "獅潭鄉" },
    { dist: "泰安鄉" }
  ],
  "彰化縣": [
    { dist: "彰化市" },
    { dist: "鹿港鎮" },
    { dist: "和美鎮" },
    { dist: "線西鄉" },
    { dist: "伸港鄉" },
    { dist: "福興鄉" },
    { dist: "秀水鄉" },
    { dist: "花壇鄉" },
    { dist: "芬園鄉" },
    { dist: "員林市" },
    { dist: "溪湖鎮" },
    { dist: "田中鎮" },
    { dist: "大村鄉" },
    { dist: "埔鹽鄉" },
    { dist: "埔心鄉" },
    { dist: "永靖鄉" },
    { dist: "社頭鄉" },
    { dist: "二水鄉" },
    { dist: "北斗鎮" },
    { dist: "二林鎮" },
    { dist: "田尾鄉" },
    { dist: "埤頭鄉" },
    { dist: "芳苑鄉" },
    { dist: "大城鄉" },
    { dist: "竹塘鄉" },
    { dist: "溪州鄉" }
  ],
  "南投縣": [
    { dist: "南投市" },
    { dist: "埔里鎮" },
    { dist: "草屯鎮" },
    { dist: "竹山鎮" },
    { dist: "集集鎮" },
    { dist: "名間鄉" },
    { dist: "鹿谷鄉" },
    { dist: "中寮鄉" },
    { dist: "魚池鄉" },
    { dist: "國姓鄉" },
    { dist: "水里鄉" },
    { dist: "信義鄉" },
    { dist: "仁愛鄉" }
  ],
  "雲林縣": [
    { dist: "斗六市" },
    { dist: "斗南鎮" },
    { dist: "虎尾鎮" },
    { dist: "西螺鎮" },
    { dist: "土庫鎮" },
    { dist: "北港鎮" },
    { dist: "古坑鄉" },
    { dist: "大埤鄉" },
    { dist: "莿桐鄉" },
    { dist: "林內鄉" },
    { dist: "二崙鄉" },
    { dist: "崙背鄉" },
    { dist: "麥寮鄉" },
    { dist: "東勢鄉" },
    { dist: "褒忠鄉" },
    { dist: "臺西鄉" },
    { dist: "元長鄉" },
    { dist: "四湖鄉" },
    { dist: "口湖鄉" },
    { dist: "水林鄉" }
  ],
  "嘉義縣": [
    { dist: "太保市" },
    { dist: "朴子市" },
    { dist: "布袋鎮" },
    { dist: "大林鎮" },
    { dist: "民雄鄉" },
    { dist: "溪口鄉" },
    { dist: "新港鄉" },
    { dist: "六腳鄉" },
    { dist: "東石鄉" },
    { dist: "義竹鄉" },
    { dist: "鹿草鄉" },
    { dist: "水上鄉" },
    { dist: "中埔鄉" },
    { dist: "竹崎鄉" },
    { dist: "梅山鄉" },
    { dist: "番路鄉" },
    { dist: "大埔鄉" },
    { dist: "阿里山鄉" }
  ],
  "屏東縣": [
    { dist: "屏東市" },
    { dist: "潮州鎮" },
    { dist: "東港鎮" },
    { dist: "恆春鎮" },
    { dist: "萬丹鄉" },
    { dist: "長治鄉" },
    { dist: "麟洛鄉" },
    { dist: "九如鄉" },
    { dist: "里港鄉" },
    { dist: "鹽埔鄉" },
    { dist: "高樹鄉" },
    { dist: "萬巒鄉" },
    { dist: "內埔鄉" },
    { dist: "竹田鄉" },
    { dist: "新埤鄉" },
    { dist: "枋寮鄉" },
    { dist: "新園鄉" },
    { dist: "崁頂鄉" },
    { dist: "林邊鄉" },
    { dist: "南州鄉" },
    { dist: "佳冬鄉" },
    { dist: "琉球鄉" },
    { dist: "車城鄉" },
    { dist: "滿州鄉" },
    { dist: "枋山鄉" },
    { dist: "三地門鄉" },
    { dist: "霧臺鄉" },
    { dist: "瑪家鄉" },
    { dist: "泰武鄉" },
    { dist: "來義鄉" },
    { dist: "春日鄉" },
    { dist: "獅子鄉" },
    { dist: "牡丹鄉" }
  ],
  "臺東縣": [
    { dist: "臺東市" },
    { dist: "成功鎮" },
    { dist: "關山鎮" },
    { dist: "卑南鄉" },
    { dist: "鹿野鄉" },
    { dist: "池上鄉" },
    { dist: "東河鄉" },
    { dist: "長濱鄉" },
    { dist: "太麻里鄉" },
    { dist: "大武鄉" },
    { dist: "綠島鄉" },
    { dist: "海端鄉" },
    { dist: "延平鄉" },
    { dist: "金峰鄉" },
    { dist: "達仁鄉" },
    { dist: "蘭嶼鄉" }
  ],
  "花蓮縣": [
    { dist: "花蓮市" },
    { dist: "鳳林鎮" },
    { dist: "玉里鎮" },
    { dist: "新城鄉" },
    { dist: "吉安鄉" },
    { dist: "壽豐鄉" },
    { dist: "光復鄉" },
    { dist: "豐濱鄉" },
    { dist: "瑞穗鄉" },
    { dist: "富里鄉" },
    { dist: "秀林鄉" },
    { dist: "萬榮鄉" },
    { dist: "卓溪鄉" }
  ],
  "澎湖縣": [
    { dist: "馬公市" },
    { dist: "湖西鄉" },
    { dist: "白沙鄉" },
    { dist: "西嶼鄉" },
    { dist: "望安鄉" },
    { dist: "七美鄉" }
  ],
  "基隆市": [
    { dist: "中正區" },
    { dist: "七堵區" },
    { dist: "暖暖區" },
    { dist: "仁愛區" },
    { dist: "中山區" },
    { dist: "安樂區" },
    { dist: "信義區" }
  ],
  "新竹市": [
    { dist: "東區" },
    { dist: "北區" },
    { dist: "香山區" }
  ],
  "嘉義市": [
    { dist: "東區" },
    { dist: "西區" }
  ],
  "臺北市": [
    { dist: "松山區" },
    { dist: "信義區" },
    { dist: "大安區" },
    { dist: "中山區" },
    { dist: "中正區" },
    { dist: "大同區" },
    { dist: "萬華區" },
    { dist: "文山區" },
    { dist: "南港區" },
    { dist: "內湖區" },
    { dist: "士林區" },
    { dist: "北投區" }
  ],
  "高雄市": [
    { dist: "鹽埕區" },
    { dist: "鼓山區" },
    { dist: "左營區" },
    { dist: "楠梓區" },
    { dist: "三民區" },
    { dist: "新興區" },
    { dist: "前金區" },
    { dist: "苓雅區" },
    { dist: "前鎮區" },
    { dist: "旗津區" },
    { dist: "小港區" },
    { dist: "鳳山區" },
    { dist: "林園區" },
    { dist: "大寮區" },
    { dist: "大樹區" },
    { dist: "大社區" },
    { dist: "仁武區" },
    { dist: "鳥松區" },
    { dist: "岡山區" },
    { dist: "橋頭區" },
    { dist: "燕巢區" },
    { dist: "田寮區" },
    { dist: "阿蓮區" },
    { dist: "路竹區" },
    { dist: "湖內區" },
    { dist: "茄萣區" },
    { dist: "永安區" },
    { dist: "彌陀區" },
    { dist: "梓官區" },
    { dist: "旗山區" },
    { dist: "美濃區" },
    { dist: "六龜區" },
    { dist: "甲仙區" },
    { dist: "杉林區" },
    { dist: "內門區" },
    { dist: "茂林區" },
    { dist: "桃源區" },
    { dist: "那瑪夏區" }
  ],
  "新北市": [
    { dist: "板橋區" },
    { dist: "三重區" },
    { dist: "中和區" },
    { dist: "永和區" },
    { dist: "新莊區" },
    { dist: "新店區" },
    { dist: "樹林區" },
    { dist: "鶯歌區" },
    { dist: "三峽區" },
    { dist: "淡水區" },
    { dist: "汐止區" },
    { dist: "瑞芳區" },
    { dist: "土城區" },
    { dist: "蘆洲區" },
    { dist: "五股區" },
    { dist: "泰山區" },
    { dist: "林口區" },
    { dist: "深坑區" },
    { dist: "石碇區" },
    { dist: "坪林區" },
    { dist: "三芝區" },
    { dist: "石門區" },
    { dist: "八里區" },
    { dist: "平溪區" },
    { dist: "雙溪區" },
    { dist: "貢寮區" },
    { dist: "金山區" },
    { dist: "萬里區" },
    { dist: "烏來區" }
  ],
  "臺中市": [
    { dist: "中區" },
    { dist: "東區" },
    { dist: "南區" },
    { dist: "西區" },
    { dist: "北區" },
    { dist: "西屯區" },
    { dist: "南屯區" },
    { dist: "北屯區" },
    { dist: "豐原區" },
    { dist: "東勢區" },
    { dist: "大甲區" },
    { dist: "清水區" },
    { dist: "沙鹿區" },
    { dist: "梧棲區" },
    { dist: "后里區" },
    { dist: "神岡區" },
    { dist: "潭子區" },
    { dist: "大雅區" },
    { dist: "新社區" },
    { dist: "石岡區" },
    { dist: "外埔區" },
    { dist: "大安區" },
    { dist: "烏日區" },
    { dist: "大肚區" },
    { dist: "龍井區" },
    { dist: "霧峰區" },
    { dist: "太平區" },
    { dist: "大里區" },
    { dist: "和平區" }
  ],
  "臺南市": [
    { dist: "新營區" },
    { dist: "鹽水區" },
    { dist: "白河區" },
    { dist: "柳營區" },
    { dist: "後壁區" },
    { dist: "東山區" },
    { dist: "麻豆區" },
    { dist: "下營區" },
    { dist: "六甲區" },
    { dist: "官田區" },
    { dist: "大內區" },
    { dist: "佳里區" },
    { dist: "學甲區" },
    { dist: "西港區" },
    { dist: "七股區" },
    { dist: "將軍區" },
    { dist: "北門區" },
    { dist: "新化區" },
    { dist: "善化區" },
    { dist: "新市區" },
    { dist: "安定區" },
    { dist: "山上區" },
    { dist: "玉井區" },
    { dist: "楠西區" },
    { dist: "南化區" },
    { dist: "左鎮區" },
    { dist: "仁德區" },
    { dist: "歸仁區" },
    { dist: "關廟區" },
    { dist: "龍崎區" },
    { dist: "永康區" },
    { dist: "東區" },
    { dist: "南區" },
    { dist: "北區" },
    { dist: "安南區" },
    { dist: "安平區" },
    { dist: "中西區" }
  ],
  "桃園市": [
    { dist: "桃園區" },
    { dist: "中壢區" },
    { dist: "大溪區" },
    { dist: "楊梅區" },
    { dist: "蘆竹區" },
    { dist: "大園區" },
    { dist: "龜山區" },
    { dist: "八德區" },
    { dist: "龍潭區" },
    { dist: "平鎮區" },
    { dist: "新屋區" },
    { dist: "觀音區" },
    { dist: "復興區" }
  ]
}